spring:
  datasource:
    batch.job.enabled: false
    datasource:
      driver-class-name: org.h2.Driver  #h2 드라이버 설정
      url: jdbc:h2:tcp://localhost/~/test  #접속 URL
      username: sa
      password: